const $=id=>document.getElementById(id), money=n=>(Number(n)||0).toFixed(2), num=id=>Number($(id)?.value)||0;
const buyerFields=[['price','商品原价 PHP',550],['activityDiscount','商品活动折扣 PHP',0],['sellerCoupon','Seller coupon PHP',0],['tiktokCoupon','TikTok Shop coupon PHP',0],['buyerShipping','买家支付运费 PHP',0]];
const localCostFields=[['purchaseRmb','商品采购成本 RMB',0],['rate','人民币兑 PHP 汇率',7.8],['domesticRmb','国内发货到集运仓成本 RMB',0],['firstMileRmb','国际头程运费 RMB',0],['storagePhp','菲律宾本土仓储费 PHP / 单',0],['warehousePhp','菲律宾仓库操作费 PHP / 单',0],['packingPhp','菲律宾本土打包费 PHP / 单',0],['lastMilePhp','菲律宾本土尾程运费 PHP / 单',0],['returnLossPhp','退货损耗 PHP / 单',0],['rejectLossPhp','拒收损耗 PHP / 单',0],['replacementPhp','坏件补发成本 PHP / 单',0],['inventoryLossPhp','库存损耗预留 PHP / 单',0],['otherLocalPhp','其他本土履约成本 PHP',0],['adPhp','广告费 PHP',0]];
const crossCostFields=[['purchaseRmb','商品采购成本 RMB',0],['rate','汇率',7.8],['domesticRmb','国内发货到集运仓成本 RMB',0],['packingRmb','国内包装成本 RMB',0],['intlPhp','国际物流 / 跨境履约成本 PHP',0],['afterSalePhp','售后损耗 PHP',0],['replacementPhp','坏件补发成本 PHP',0],['otherPhp','其他履约成本 PHP',0],['adPhp','广告费 PHP',0]];
const localFeeDefaults=[['transaction','平台交易手续费',true,'percent',2.24],['commission','TikTok Shop 佣金费',true,'percent',7.2],['affiliate','达人 / 联盟佣金',true,'percent',10],['superCoupon','超级优惠券服务费',false,'percent',5],['sfp','物流服务费 / SFP 服务费',true,'percent',5.5],['growth','商家成长服务费',true,'percent',1],['handling','订单处理手续费',true,'fixed',3],['protection','物流保障服务费',true,'fixed',2],['shippingSubsidy','卖家承担运费补贴',false,'fixed',0],['promo','其他促销活动抽点',false,'percent',0],['flash','秒杀服务费',false,'percent',3],['other','其他平台费用',false,'fixed',0]];
const crossFeeDefaults=[['commission','平台佣金',false,'percent',0],['transaction','交易手续费',false,'percent',0],['affiliate','达人佣金',false,'percent',0],['sfp','SFP 服务费',false,'percent',0],['promo','促销活动服务费',false,'percent',0],['flash','秒杀服务费',false,'percent',0],['otherFixed','其他固定费用',false,'fixed',0],['otherPercent','其他比例费用',false,'percent',0]];
const cases={A:{price:550,disc:225,fees:{transaction:6.90,commission:23.40,affiliate:14.75,superCoupon:16.25,sfp:17.88,handling:3,protection:2,growth:3.25},total:87.43,settle:237.57},B:{price:550,disc:235,fees:{transaction:8.40,commission:22.68,affiliate:32.40,superCoupon:15.75,sfp:17.32,handling:3,protection:2,growth:3.15},total:104.70,settle:210.30}};
const scenarios=['正常销售','达人带货','平台活动','直播秒杀']; let mode='local', lastText='';
function inputHtml(prefix, fields){return fields.map(f=>`<label>${f[1]}<input id="${prefix}_${f[0]}" data-save type="number" step="0.01" value="${f[2]}"></label>`).join('')}
function feeHtml(prefix, fees, withdraw=false){let h=fees.map(f=>`<div class="fee-row"><label class="checkline"><input id="${prefix}_fee_${f[0]}_on" data-save type="checkbox" ${f[2]?'checked':''}>${f[1]}</label><label>计算方式<select id="${prefix}_fee_${f[0]}_type" data-save><option value="percent" ${f[3]=='percent'?'selected':''}>按比例 %</option><option value="fixed" ${f[3]=='fixed'?'selected':''}>固定 PHP</option></select></label><label>费率 / 金额<input id="${prefix}_fee_${f[0]}_value" data-save type="number" step="0.01" value="${f[4]}"></label><label>手动固定金额<input id="${prefix}_fee_${f[0]}_manual" data-save type="number" step="0.01" placeholder="留空按规则"></label><div><span id="${prefix}_fee_${f[0]}_out">0.00</span></div></div>`).join('');
 if(withdraw) h+=`<div class="fee-row"><label class="checkline"><input id="${prefix}_withdraw_on" data-save type="checkbox" checked>提现手续费</label><label>计算方式<select id="${prefix}_withdraw_base" data-save><option value="after" selected>按平台扣费后结算金额</option><option value="base">按商家折扣后小计</option><option value="off">关闭</option></select></label><label>费率 %<input id="${prefix}_withdraw_rate" data-save type="number" step="0.01" value="1"></label><label>手动固定金额<input id="${prefix}_withdraw_manual" data-save type="number" step="0.01" placeholder="留空按规则"></label><div><span id="${prefix}_withdraw_out">0.00</span></div></div>`;
 return h}
function scenarioHtml(prefix){return scenarios.map((s,i)=>`<div class="scenario"><b>${s}</b>${['商家总折扣','达人佣金%','超级券%','促销抽点%','秒杀%','运费补贴','售后损耗','广告费'].map((n,j)=>`<label>${n}<input id="${prefix}_sc_${i}_${j}" data-save type="number" step="0.01" value="0"></label>`).join('')}<div id="${prefix}_sc_${i}_out" class="scenario-output"></div></div>`).join('')}
function init(){['local','cross'].forEach(p=>{$(p+'Buyer').innerHTML=inputHtml(p,buyerFields);$(p+'Targets').innerHTML=[10,20,30].map((v,i)=>`<label>目标利润率 ${i+1}<input id="${p}_target_${i}" data-save type="number" step="0.01" value="${v}"></label>`).join('');$(p+'Scenarios').innerHTML=scenarioHtml(p)});$('localCosts').innerHTML=inputHtml('localCost',localCostFields);$('crossCosts').innerHTML=inputHtml('crossCost',crossCostFields);$('localFees').innerHTML=feeHtml('local',localFeeDefaults,true);$('crossFees').innerHTML=feeHtml('cross',crossFeeDefaults,true);load();bind();calc()}
function storageMode(el){return (el.id.startsWith('cross')||el.id.startsWith('crossCost'))?'cross':'local'}
function save(){document.querySelectorAll('[data-save]').forEach(el=>localStorage.setItem(storageMode(el)+':'+el.id,el.type==='checkbox'?el.checked:el.value))}
function load(){document.querySelectorAll('[data-save]').forEach(el=>{let v=localStorage.getItem((el.id.startsWith('cross')||el.id.startsWith('crossCost')?'cross':'local')+':'+el.id); if(v!=null) el.type==='checkbox'?el.checked=v==='true':el.value=v})}
function fee(prefix, def, base){let total=0, detail={}; def.forEach(f=>{let id=`${prefix}_fee_${f[0]}`, on=$(id+'_on').checked, manual=$(id+'_manual').value; let val=0;if(on){val=manual!==''?Number(manual):($(id+'_type').value==='percent'?base*num(id+'_value')/100:num(id+'_value'))}$(id+'_out').textContent=money(val);detail[f[0]]=val;total+=val});return {total,detail}}
function calc(p=mode){let price=num(`${p}_price`), act=num(`${p}_activityDiscount`), sell=num(`${p}_sellerCoupon`), tik=num(`${p}_tiktokCoupon`), ship=num(`${p}_buyerShipping`);let buyerSub=price-act-sell-tik; let buyerPay=buyerSub+ship; if($(`${p}BuyerSubtotal`)){$(`${p}BuyerSubtotal`).textContent=money(buyerSub);$(`${p}BuyerPay`).textContent=money(buyerPay)}let md=$(`${p}DiscountMode`).value==='auto'?act+sell:num(`${p}MerchantDiscount`); if($(`${p}DiscountMode`).value==='auto') $(`${p}MerchantDiscount`).value=money(md); let base=price-md; let defs=p==='local'?localFeeDefaults:crossFeeDefaults; let fr=fee(p,defs,base); let before=base-fr.total; let wm=$(`${p}_withdraw_manual`).value; let w=0;if($(`${p}_withdraw_on`).checked&&$(`${p}_withdraw_base`).value!=='off') w=wm!==''?Number(wm):($(`${p}_withdraw_base`).value==='base'?base:before)*num(`${p}_withdraw_rate`)/100;$(`${p}_withdraw_out`).textContent=money(w); let settlement=before-w;
 if($(`${p}SettlementBase`)) $(`${p}SettlementBase`).textContent=money(base); if($(`${p}PlatformFees`)) $(`${p}PlatformFees`).textContent=money(fr.total); if($(`${p}WithdrawalFee`)) $(`${p}WithdrawalFee`).textContent=money(w); if($(`${p}Settlement`)) $(`${p}Settlement`).textContent=money(settlement); let costs=p==='local'?localCosts():crossCosts(); let profit=settlement-costs.total; let marginBase=base?profit/base*100:0, marginPrice=price?profit/price*100:0; renderResults(p,{base,platform:fr.total,w,settlement,costs,profit,marginBase,marginPrice,price,md}); validateCase(base,fr.total,settlement); calcScenarios(p); save();}
function localCosts(){let r=num('localCost_rate');let total=num('localCost_purchaseRmb')*r+num('localCost_domesticRmb')*r+num('localCost_firstMileRmb')*r+['storagePhp','warehousePhp','packingPhp','lastMilePhp','returnLossPhp','rejectLossPhp','replacementPhp','inventoryLossPhp','otherLocalPhp','adPhp'].reduce((s,k)=>s+num('localCost_'+k),0);return{total}}
function crossCosts(){let r=num('crossCost_rate');return{total:num('crossCost_purchaseRmb')*r+num('crossCost_domesticRmb')*r+num('crossCost_packingRmb')*r+['intlPhp','afterSalePhp','replacementPhp','otherPhp','adPhp'].reduce((s,k)=>s+num('crossCost_'+k),0)}}
function renderResults(p,r){let cls=r.profit<0?'loss':(r.marginBase<10?'risk':'profit'); let rate=sumRate(p); let fixed=sumFixed(p)+r.costs.total; let breakeven=(fixed)/(1-rate); let targets=[0,1,2].map(i=>num(`${p}_target_${i}`)); let suggest=targets.map(t=> fixed/(1-rate-t/100)); $(p+'Results').innerHTML=`<div>商家折扣后小计 <b>${money(r.base)}</b></div><div>平台费用总额 <b>${money(r.platform)}</b></div><div>提现手续费 <b>${money(r.w)}</b></div><div>预计结算总金额 <b>${money(r.settlement)}</b></div><div>商品与履约成本 <b>${money(r.costs.total)}</b></div><div>最终净利润 <b class="${cls}">${money(r.profit)}</b></div><div>结算收入利润率 <b class="${cls}">${money(r.marginBase)}%</b></div><div>原价利润率 <b class="${cls}">${money(r.marginPrice)}%</b></div><div>保本原价 <b>${money(breakeven)}</b></div><div>建议原价 <b>${targets.map((t,i)=>`${t}%：${money(suggest[i])}`).join('<br>')}</b></div>`; lastText=`${p==='local'?'本土':'跨境'}模式\n商家折扣后小计 ${money(r.base)}\n平台费用总额 ${money(r.platform)}\n提现手续费 ${money(r.w)}\n预计结算总金额 ${money(r.settlement)}\n成本 ${money(r.costs.total)}\n最终净利润 ${money(r.profit)}\n利润率 ${money(r.marginBase)}%`;}
function sumRate(p){let defs=p==='local'?localFeeDefaults:crossFeeDefaults, rate=0;defs.forEach(f=>{if($(`${p}_fee_${f[0]}_on`).checked&&$(`${p}_fee_${f[0]}_type`).value==='percent'&&!$(`${p}_fee_${f[0]}_manual`).value)rate+=num(`${p}_fee_${f[0]}_value`)/100});rate+=($(`${p}_withdraw_on`).checked&&$(`${p}_withdraw_base`).value!=='off'&&!$(`${p}_withdraw_manual`).value)?num(`${p}_withdraw_rate`)/100:0;return Math.min(rate,.95)}
function sumFixed(p){let defs=p==='local'?localFeeDefaults:crossFeeDefaults, fixed=0;defs.forEach(f=>{if($(`${p}_fee_${f[0]}_on`).checked&&($(`${p}_fee_${f[0]}_type`).value==='fixed'||$(`${p}_fee_${f[0]}_manual`).value))fixed+=Number($(`${p}_fee_${f[0]}_manual`).value||$(`${p}_fee_${f[0]}_value`).value)||0});return fixed}
function calcScenarios(p){for(let i=0;i<4;i++){let price=num(`${p}_price`), base=price-num(`${p}_sc_${i}_0`), fees=base*(num(`${p}_sc_${i}_1`)+num(`${p}_sc_${i}_2`)+num(`${p}_sc_${i}_3`)+num(`${p}_sc_${i}_4`))/100+num(`${p}_sc_${i}_5`), settle=base-fees, costs=(p==='local'?localCosts():crossCosts()).total+num(`${p}_sc_${i}_6`)+num(`${p}_sc_${i}_7`), profit=settle-costs, margin=base?profit/base*100:0; $(`${p}_sc_${i}_out`).innerHTML=`预计结算金额：${money(settle)} ｜ 最终净利润：<b class="${profit<0?'loss':margin<10?'risk':'profit'}">${money(profit)}</b> ｜ 利润率：${money(margin)}% ｜ ${profit<0?'亏损':'盈利'} ｜ 保本原价：${money(costs+fees)}`}}
function validateCase(base,total,settle){let c=cases[$('localCase').value]; if(!c){$('caseStatus').textContent='请选择案例进行校验。';return} let diff=settle-c.settle, ok=Math.abs(diff)<0.02; $('caseStatus').innerHTML=`<span class="${ok?'pass':'fail'}">${ok?'结算单校验通过':'结算单校验不一致'}</span><br>后台真实结算金额：${money(c.settle)} ｜ 计算结算金额：${money(settle)} ｜ 差额：${money(diff)}<br>真实平台费用：${money(c.total)} ｜ 计算平台费用：${money(total)} ｜ 商家折扣后小计：${money(base)}`}
function applyCase(k=$('localCase').value){let c=cases[k]; if(!c)return; mode='local';$('localTab').click();$('local_price').value=c.price;$('localMerchantDiscount').value=c.disc;$('localDiscountMode').value='manual';localFeeDefaults.forEach(f=>{let id=`local_fee_${f[0]}`;$(`${id}_on`).checked=!!c.fees[f[0]];$(`${id}_manual`).value=c.fees[f[0]]??''});$('local_withdraw_on').checked=false;calc('local')}
function resetDefaults(){if(mode==='local')localFeeDefaults.forEach(f=>{let id=`local_fee_${f[0]}`;$(`${id}_on`).checked=f[2];$(`${id}_type`).value=f[3];$(`${id}_value`).value=f[4];$(`${id}_manual`).value=''});else crossFeeDefaults.forEach(f=>{let id=`cross_fee_${f[0]}`;$(`${id}_on`).checked=f[2];$(`${id}_type`).value=f[3];$(`${id}_value`).value=f[4];$(`${id}_manual`).value=''});calc()}
function bind(){document.addEventListener('input',()=>calc());document.addEventListener('change',e=>{if(e.target.id==='localCase')applyCase(e.target.value);else calc()});$('localTab').onclick=()=>{mode='local';$('localTab').classList.add('active');$('crossTab').classList.remove('active');$('localMode').classList.add('active');$('crossMode').classList.remove('active');calc()};$('crossTab').onclick=()=>{mode='cross';$('crossTab').classList.add('active');$('localTab').classList.remove('active');$('crossMode').classList.add('active');$('localMode').classList.remove('active');calc()};$('calcBtn').onclick=()=>calc();$('clearBtn').onclick=()=>{document.querySelectorAll('.mode.active input').forEach(i=>{if(i.type==='checkbox')i.checked=false;else i.value=0});calc()};$('defaultsBtn').onclick=resetDefaults;$('caseBtn').onclick=()=>applyCase($('localCase').value==='none'?'A':$('localCase').value);$('copyBtn').onclick=()=>navigator.clipboard?.writeText(lastText);$('exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lastText],{type:'text/plain'}));a.download='tiktok-profit-result.txt';a.click()}}
init();
