const $=id=>document.getElementById(id), money=n=>(Number(n)||0).toFixed(2), round2=n=>Math.round((Number(n)||0)*100)/100, num=id=>Number($(id)?.value)||0;
const buyerFields=[['price','商品原价 PHP',550],['activityDiscount','商家活动折扣 PHP',0],['sellerCoupon','Seller Coupon PHP',0],['tiktokCoupon','TikTok / Platform Coupon（平台承担，仅展示）PHP',0],['buyerShipping','买家支付运费 PHP',0]];
const localCostFields=[['purchaseRmb','产品采购成本 RMB',0],['rate','1 RMB = X PHP',7.8],['domesticRmb','国内发货到集运仓成本 RMB',0],['firstMileRmb','国际物流成本 RMB',0],['packingPhp','包装成本 PHP / 单',0],['otherLocalPhp','其他成本 PHP',0]];
const crossCostFields=[['purchaseRmb','产品采购成本 RMB',0],['rate','1 RMB = X PHP',7.8],['domesticRmb','国内发货到集运仓成本 RMB',0],['packingRmb','包装成本 RMB',0],['intlPhp','国际物流 / 跨境履约成本 PHP',0],['otherPhp','其他成本 PHP',0]];
const localFeeDefaults=[
 ['commission','TikTok Shop 佣金费',true,'percent',7.2,'merchant'],['transaction','平台交易手续费',true,'percent',2.24,'buyer'],['sfp','物流服务费 / SFP 服务费',true,'percent',5.5,'merchant'],['growth','商家成长服务费',true,'percent',1,'merchant'],['handling','订单处理手续费',true,'fixed',3,'fixed'],['affiliate','达人 / 联盟佣金',true,'percent',10,'merchant'],['superCoupon','超级优惠券服务费',true,'percent',4,'merchant'],['flash','秒杀服务费',false,'percent',3,'merchant'],['promo','商家活动扣点',false,'percent',0,'merchant'],['protection','物流保障服务费',false,'fixed',2,'fixed'],['otherPlatform','其他平台费用',false,'fixed',0,'fixed']
];
const crossFeeDefaults=[['commission','平台佣金',false,'percent',0,'merchant'],['transaction','交易手续费',false,'percent',0,'buyer'],['affiliate','达人佣金',false,'percent',0,'merchant'],['sfp','SFP 服务费',false,'percent',0,'merchant'],['promo','促销活动服务费',false,'percent',0,'merchant'],['flash','秒杀服务费',false,'percent',0,'merchant'],['otherFixed','其他固定费用',false,'fixed',0,'fixed']];
const replayFields=[['actualSettlement','实际平台结算金额 PHP',0],['actualAffiliateRate','实际达人佣金费率 %',0],['actualAffiliate','实际达人佣金金额 PHP',0],['actualOtherPlatform','实际其他平台费用金额 PHP',0],['actualSellerShipping','实际商家承担运费 PHP',0],['actualAd','实际广告分摊费用 PHP',0],['actualRiskLoss','实际退货、拒收、取消相关损失 PHP',0]];
let shippingMode='local', calculationMode='estimate', lastText='';
function inputHtml(prefix, fields){return fields.map(f=>`<label>${f[1]}<input id="${prefix}_${f[0]}" data-save type="number" step="0.01" value="${f[2]}"></label>`).join('')}
function feeHtml(prefix, fees){return fees.map(f=>`<div class="fee-row"><label class="checkline"><input id="${prefix}_fee_${f[0]}_on" data-save type="checkbox" ${f[2]?'checked':''}>${f[1]}</label><label>计算方式<select id="${prefix}_fee_${f[0]}_type" data-save><option value="percent" ${f[3]=='percent'?'selected':''}>按比例 %</option><option value="fixed" ${f[3]=='fixed'?'selected':''}>固定 PHP 金额</option></select></label><label>计费基数<select id="${prefix}_fee_${f[0]}_base" data-save><option value="merchant" ${f[5]=='merchant'?'selected':''}>商家优惠后商品金额</option><option value="buyer" ${f[5]=='buyer'?'selected':''}>买家最终付款金额</option><option value="manual">手动输入金额</option><option value="fixed" ${f[5]=='fixed'?'selected':''}>固定 PHP 金额</option></select></label><label>费率 / 金额<input id="${prefix}_fee_${f[0]}_value" data-save type="number" step="0.01" value="${f[4]}"></label><label>手动基数 / 实际金额<input id="${prefix}_fee_${f[0]}_manual" data-save type="number" step="0.01" placeholder="留空按规则"></label><div><span id="${prefix}_fee_${f[0]}_out">0.00</span></div></div>`).join('')}
function sellerHtml(prefix){return `<div class="grid three"><label class="checkline"><input id="${prefix}_ad_on" data-save type="checkbox">广告费用</label><label>广告输入方式<select id="${prefix}_ad_type" data-save><option value="fixed">每单固定广告费 RMB / 单</option><option value="percent">按成交金额比例 %</option></select></label><label>广告费 RMB / 费率<input id="${prefix}_ad_value" data-save type="number" step="0.01" value="0"></label><label>退货率 %<input id="${prefix}_return_rate" data-save type="number" min="0" max="100" step="0.01" value="0"></label><label>拒收率 %<input id="${prefix}_reject_rate" data-save type="number" min="0" max="100" step="0.01" value="0"></label><label>取消率 %<input id="${prefix}_cancel_rate" data-save type="number" min="0" max="100" step="0.01" value="0"></label><label>商家承担运费 PHP<input id="${prefix}_seller_shipping" data-save type="number" step="0.01" value="0"></label><label>其他卖家结算端费用 PHP<input id="${prefix}_seller_other" data-save type="number" step="0.01" value="0"></label></div><p class="hint">售后与订单风险预留是经营测算预留，不代表 TikTok 每一笔退款、拒收或取消订单的实际结算规则完全一致。</p><div id="${prefix}SellerResults" class="result-grid"></div>`}
function replayHtml(prefix){return `<label class="checkline switch"><input id="${prefix}_replay_on" data-save type="checkbox">真实订单复盘模式</label><div id="${prefix}ReplayInputs" class="grid three">${replayFields.map(f=>`<label>${f[1]}<input id="${prefix}_replay_${f[0]}" data-save type="number" step="0.01" value="${f[2]}"></label>`).join('')}</div><div id="${prefix}ReplayResults" class="result-grid"></div>`}
function init(){['local','cross'].forEach(p=>{$(p+'Buyer').innerHTML=inputHtml(p,buyerFields);$(p+'Targets').innerHTML=[10,20,30].map((v,i)=>`<label>目标利润率 ${i+1}<input id="${p}_target_${i}" data-save type="number" step="0.01" value="${v}"></label>`).join('')});$('localCosts').innerHTML=inputHtml('localCost',localCostFields);$('crossCosts').innerHTML=inputHtml('crossCost',crossCostFields);$('localFees').innerHTML=feeHtml('local',localFeeDefaults);$('crossFees').innerHTML=feeHtml('cross',crossFeeDefaults);$('localSeller').innerHTML=sellerHtml('local');$('localReplay').innerHTML=replayHtml('local');$('crossSeller').innerHTML=sellerHtml('cross');$('crossReplay').innerHTML=replayHtml('cross');load();bind();applyModes();calc()}
function storageMode(el){return (el.id.startsWith('cross')||el.id.startsWith('crossCost'))?'cross':'local'}
function save(){localStorage.setItem('shippingMode',shippingMode);localStorage.setItem('calculationMode',calculationMode);document.querySelectorAll('[data-save]').forEach(el=>localStorage.setItem(storageMode(el)+':'+el.id,el.type==='checkbox'?el.checked:el.value))}
function normalizeShippingMode(v){return v==='cross'||v==='local'?v:'local'}
function normalizeCalculationMode(v){return v==='replay'||v==='estimate'?v:'estimate'}
function loadModes(){let savedShipping=localStorage.getItem('shippingMode'), savedCalculation=localStorage.getItem('calculationMode');shippingMode=normalizeShippingMode(savedShipping);calculationMode=normalizeCalculationMode(savedCalculation);if(savedShipping==null&&savedCalculation==null){let legacy=localStorage.getItem('mode');if(legacy==='local'||legacy==='cross') shippingMode=legacy; else if(legacy==='replay'||legacy==='estimate') calculationMode=legacy}}
function load(){loadModes();document.querySelectorAll('[data-save]').forEach(el=>{let v=localStorage.getItem(storageMode(el)+':'+el.id); if(v!=null) el.type==='checkbox'?el.checked=v==='true':el.value=v})}
function fee(prefix, def, merchant, buyer){let total=0, detail={}; def.forEach(f=>{let id=`${prefix}_fee_${f[0]}`, on=$(id+'_on').checked, manual=$(id+'_manual').value, type=$(id+'_type').value, baseSel=$(id+'_base').value; let val=0;if(on){if(manual!=='' && (baseSel==='fixed'||type==='fixed')) val=Number(manual); else if(type==='fixed'||baseSel==='fixed') val=num(id+'_value'); else {let b=baseSel==='buyer'?buyer:baseSel==='manual'?num(id+'_manual'):merchant; val=b*num(id+'_value')/100}} val=round2(val);$(id+'_out').textContent=money(val);detail[f[0]]=val;total=round2(total+val)});return {total,detail}}
function baseAmounts(p){let price=num(`${p}_price`), act=num(`${p}_activityDiscount`), sell=num(`${p}_sellerCoupon`), tik=num(`${p}_tiktokCoupon`), ship=num(`${p}_buyerShipping`);let merchant=Math.max(0,price-act-sell), buyer=merchant+ship;return{price,act,sell,tik,ship,merchant,buyer}}
function calc(p=shippingMode){let a=baseAmounts(p); if($(`${p}BuyerSubtotal`)){$(`${p}BuyerSubtotal`).textContent=money(a.merchant);$(`${p}BuyerPay`).textContent=money(a.buyer)} if($(`${p}DiscountMode`)?.value==='auto') $(`${p}MerchantDiscount`).value=money(a.act+a.sell); let defs=p==='local'?localFeeDefaults:crossFeeDefaults; let fr=fee(p,defs,a.merchant,a.buyer); if($(`${p}_replay_on`)?.checked){let ar=num(`${p}_replay_actualAffiliateRate`), af=num(`${p}_replay_actualAffiliate`), op=num(`${p}_replay_actualOtherPlatform`); if(af>0 || ar>0){let actualAffiliate=af>0?af:round2(a.merchant*ar/100); fr.total=round2(fr.total-(fr.detail.affiliate||0)+actualAffiliate); fr.detail.affiliate=round2(actualAffiliate)} if(op>0){fr.total=round2(fr.total+op); fr.detail.actualOtherPlatform=round2(op)}} let estimated=round2(a.merchant-fr.total); if($(`${p}SettlementBase`)) $(`${p}SettlementBase`).textContent=money(a.merchant); if($(`${p}PlatformFees`)) $(`${p}PlatformFees`).textContent=money(fr.total); if($(`${p}Settlement`)) $(`${p}Settlement`).textContent=money(estimated); let seller=sellerSide(p,estimated,a); let costs=p==='local'?localCosts():crossCosts(); let profit=round2(seller.adjusted-costs.total); let margin=a.merchant?profit/a.merchant*100:0; renderResults(p,{...a,fees:fr,estimated,seller,costs,profit,margin}); save(); return {platformTotal:fr.total,estimatedSettlement:estimated,adjustedSettlement:seller.adjusted}}
function sellerSide(p,estimated,a){let rate=num(`${p}Cost_rate`)||num('localCost_rate')||7.8, adOn=$(`${p}_ad_on`)?.checked, adRmb=0, adPhp=0;if(adOn){if($(`${p}_ad_type`).value==='fixed') adRmb=num(`${p}_ad_value`); else adRmb=a.buyer*num(`${p}_ad_value`)/100/rate; adPhp=round2(adRmb*rate)}let rr=num(`${p}_return_rate`), jr=num(`${p}_reject_rate`), cr=num(`${p}_cancel_rate`), raw=rr+jr+cr, sum=Math.min(100,raw), scale=raw>100?100/raw:1;let ret=round2(estimated*rr*scale/100), rej=round2(estimated*jr*scale/100), can=round2(estimated*cr*scale/100), risk=round2(ret+rej+can);let ship=num(`${p}_seller_shipping`), other=num(`${p}_seller_other`);if($(`${p}_replay_on`)?.checked){let actualShip=num(`${p}_replay_actualSellerShipping`), actualAd=num(`${p}_replay_actualAd`), actualRisk=num(`${p}_replay_actualRiskLoss`); if(actualShip>0) ship=actualShip; if(actualAd>0){adPhp=actualAd; adRmb=rate?actualAd/rate:0} if(actualRisk>0){risk=actualRisk; ret=actualRisk; rej=0; can=0}}let adjusted=round2(estimated-risk-adPhp-ship-other);return{adRmb,adPhp,rr,jr,cr,sum,ret,rej,can,risk,ship,other,adjusted}}
function localCosts(){let r=num('localCost_rate');return{total:round2(num('localCost_purchaseRmb')*r+num('localCost_domesticRmb')*r+num('localCost_firstMileRmb')*r+num('localCost_packingPhp')+num('localCost_otherLocalPhp'))}}
function crossCosts(){let r=num('crossCost_rate');return{total:round2(num('crossCost_purchaseRmb')*r+num('crossCost_domesticRmb')*r+num('crossCost_packingRmb')*r+num('crossCost_intlPhp')+num('crossCost_otherPhp'))}}
function renderResults(p,r){let cls=r.profit<0?'loss':(r.margin<10?'risk':'profit'), feeLines=Object.entries(r.fees.detail).map(([k,v])=>`<div>${(p==='local'?localFeeDefaults:crossFeeDefaults).find(f=>f[0]===k)?.[1]||k} <b>${money(v)}</b></div>`).join('');let feeRatio=r.merchant?r.fees.total/r.merchant*100:0, breakeven=round2(r.costs.total+r.fees.total+r.seller.risk+r.seller.adPhp+r.seller.ship+r.seller.other), targets=[0,1,2].map(i=>num(`${p}_target_${i}`));let suggest=targets.map(t=>r.merchant?breakeven/(1-t/100):0);$(p+'Results').innerHTML=`<div>商品原价 <b>${money(r.price)}</b></div><div>商家活动折扣 <b>${money(r.act)}</b></div><div>Seller Coupon <b>${money(r.sell)}</b></div><div>商家优惠后商品金额 <b>${money(r.merchant)}</b></div><div>买家支付运费 <b>${money(r.ship)}</b></div><div>买家最终付款金额 <b>${money(r.buyer)}</b></div>${feeLines}<div>平台总费用 <b>${money(r.fees.total)}</b></div><div>平台总费用占商家优惠后商品金额 <b>${money(feeRatio)}%</b></div><div>预计平台结算金额 <b>${money(r.estimated)}</b></div><div>产品总成本 <b>${money(r.costs.total)}</b></div><div>最终利润 <b class="${cls}">${money(r.profit)}</b></div><div>利润率 <b class="${cls}">${money(r.margin)}%</b></div><div>保本售价 <b>${money(breakeven)}</b></div><div>目标利润售价 <b>${targets.map((t,i)=>`${t}%：${money(suggest[i])}`).join('<br>')}</b></div>`;$(`${p}SellerResults`).innerHTML=`<div>广告费（RMB）<b>${money(r.seller.adRmb)}</b></div><div>广告费（换算后 PHP）<b>${money(r.seller.adPhp)}</b></div><div>退货率 / 退货损耗预留金额 <b>${money(r.seller.rr)}% / ${money(r.seller.ret)}</b></div><div>拒收率 / 拒收损耗预留金额 <b>${money(r.seller.jr)}% / ${money(r.seller.rej)}</b></div><div>取消率 / 取消损耗预留金额 <b>${money(r.seller.cr)}% / ${money(r.seller.can)}</b></div><div>总风险率 <b>${money(r.seller.sum)}%</b></div><div>总风险预留金额 <b>${money(r.seller.risk)}</b></div><div>商家承担运费 <b>${money(r.seller.ship)}</b></div><div>其他卖家结算端费用 <b>${money(r.seller.other)}</b></div><div>风险调整后卖家结算金额 <b>${money(r.seller.adjusted)}</b></div>`;renderReplay(p,r);lastText=`超级 TikTok Shop 菲律宾利润计算器\n${calculationMode==='estimate'?'预估定价':'真实订单复盘'} / ${p==='local'?'菲律宾本土发货':'跨境发货'}\n平台总费用 ${money(r.fees.total)}\n预计平台结算金额 ${money(r.estimated)}\n风险调整后卖家结算金额 ${money(r.seller.adjusted)}\n产品总成本 ${money(r.costs.total)}\n最终利润 ${money(r.profit)}\n利润率 ${money(r.margin)}%`}
function renderReplay(p,r){let on=$(`${p}_replay_on`)?.checked;if(!on){$(`${p}ReplayResults`).innerHTML='<div class="notice">开启真实订单复盘模式后，可录入平台账单实际金额并对比差异。</div>';return}let actual=num(`${p}_replay_actualSettlement`), diff=round2(actual-r.estimated), ratio=r.estimated?diff/r.estimated*100:0;$(`${p}ReplayResults`).innerHTML=`<div>计算器预计结算金额 <b>${money(r.estimated)}</b></div><div>实际平台结算金额 <b>${money(actual)}</b></div><div>两者差额 <b>${money(diff)}</b></div><div>差额比例 <b>${money(ratio)}%</b></div><div class="notice">可能原因：平台优惠券、未录入活动费用、实际达人佣金不同、四舍五入、物流保障费、广告费用、商家运费、退款/拒收/取消造成的损失、其他平台服务费。</div>`}
function resetDefaults(){let defs=shippingMode==='local'?localFeeDefaults:crossFeeDefaults;defs.forEach(f=>{let id=`${shippingMode}_fee_${f[0]}`;$(`${id}_on`).checked=f[2];$(`${id}_type`).value=f[3];$(`${id}_value`).value=f[4];$(`${id}_base`).value=f[5];$(`${id}_manual`).value=''});calc()}
function setShippingMode(next){shippingMode=normalizeShippingMode(next);applyModes();calc()}
function setCalculationMode(next){calculationMode=normalizeCalculationMode(next);applyModes();calc()}
function applyModes(){let isLocal=shippingMode==='local', isReplay=calculationMode==='replay';$('localTab').classList.toggle('active',isLocal);$('crossTab').classList.toggle('active',!isLocal);$('estimateTab').classList.toggle('active',!isReplay);$('replayTab').classList.toggle('active',isReplay);$('localMode').classList.toggle('active',isLocal);$('crossMode').classList.toggle('active',!isLocal);document.body.dataset.calculationMode=calculationMode;['local','cross'].forEach(p=>{let replayOn=$(`${p}_replay_on`);if(replayOn) replayOn.checked=isReplay})}
function bind(){document.addEventListener('input',()=>calc());document.addEventListener('change',e=>{if(e.target?.id?.endsWith('_replay_on')) calculationMode=e.target.checked?'replay':'estimate';applyModes();calc()});$('localTab').onclick=()=>setShippingMode('local');$('crossTab').onclick=()=>setShippingMode('cross');$('estimateTab').onclick=()=>setCalculationMode('estimate');$('replayTab').onclick=()=>setCalculationMode('replay');$('calcBtn').onclick=()=>calc();$('clearBtn').onclick=()=>{document.querySelectorAll('.mode.active input').forEach(i=>{if(i.type==='checkbox')i.checked=false;else i.value=0});calculationMode='estimate';applyModes();calc()};$('defaultsBtn').onclick=resetDefaults;$('copyBtn').onclick=()=>navigator.clipboard?.writeText(lastText);$('exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lastText],{type:'text/plain'}));a.download='tiktok-profit-result.txt';a.click()}}
if(typeof document!=='undefined') init();
